import Head from 'next/head'
import Image from 'next/image'
import { Josefin_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'
// import NavBar from '../components/Navbar'

const inter = Josefin_Sans({ subsets: ['latin'] })

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>About MeTime</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}> */}
          <p>
          </p>
          {/* <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
            </a>
          </div> */}
        {/* </div> */}

        {/* <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/MeTime Logo.svg"
            alt="Next.js Logo"
            width={500}
            height={500}
            priority
          />
        </div> */}


<div className={styles.center}>
        <h1 className={inter.className}>
              About MeTime
            </h1>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/Group.svg"
            alt="Next.js Logo"
            width={400}
            height={400}
            priority
          />
        </div>

        <div className={styles.grid1}>
          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              The Problem 
            </h2>
            <p className={inter.className}>
            A rising problem in United States currently is stress and burnout, and has grown especially throughout the pandemic. </p>
<p className={inter.className}>“79% of employees had experienced work-related stress… Nearly 3 in 5 employees reported negative impacts of work-related stress, including lack of interest, motivation, or energy, and lack of effort at work.”1</p>
<p className={inter.className}>“Among all respondents, 80% believe COVID-19 has impacted workplace burnout.”2</p>
<p className={inter.className}>In addition to this we found that another issue that is arising is work life balance and finding time to find new interests and hobbies. </p>
<p className={inter.className}>“Mental health benefits of hobbies: Reduced stress, enhanced well-being, improved social connection, decreases in depression and anxiety, and improved mental health.”3
Source(s): (APA 2021, Work and Well-being Survey of 1,501 U.S. adult workers)1 | (Forbes, 2021)2 | (Utah State University, 2021)3
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              The Solution
            </h2>
            <p className={inter.className}>
            The MeTime application will allow users to better organize free time and explore new interests. 
The user is able to import their digital calendar and the city they are located in.
The user will also be able to go through an onboarding process where they can select their interests and activities. 
A MeTime block will appear when the user has free time for a 30 minute to 1 hour block and suggest nearby activities corresponding with their interests..&nbsp;
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Our Values 
            </h2>
            <p className={inter.className}>
              We understand that it is important for all of us to solve this problem. As college students, we try to achieve this work-life balance on a daily basis from trying to make friends, spend time on our hobbies, and do well in school.
We have talked about each other’s interests and how we don’t feel like we have enough time in the day.
This is an issue we deal with on an everyday basis along with millions of other people in America. So we would love to make a difference and help combat this problem!  
            </p>
          </a>

          
        </div>
      </main>
    </>
  )
}
