import Head from 'next/head'
import Image from 'next/image'
import { Josefin_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Josefin_Sans({ subsets: ['latin'] })

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>MeTime Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/MeTime Logo.svg"
            alt="Next.js Logo"
            width={500}
            height={500}
            priority
          />
        </div>


        <div className={styles.griddy}>
          <a
            href="/about"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              About Us 
            </h2>
            <p className={inter.className}>
              Learn more about our project, values, and history.
            </p>
          </a>

          <a
            href="/team"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              The Team
            </h2>
            <p className={inter.className}>
              Meet the minds behind MeTime.
            </p>
          </a>

          <a
            href="/login"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              MeTime Portal
            </h2>
            <p className={inter.className}>
              If you are a new or returning, click here to continue! 
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
