import Head from 'next/head'
import Image from 'next/image'
import { Josefin_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Josefin_Sans({ subsets: ['latin'] })

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>MeTime Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/metimeman.svg"
            alt="Next.js Logo"
            width={500}
            height={500}
            priority
          />
        </div>


        <div className={styles.grid}>
          <a
            href="/about"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              MeTime Block  
            </h2>
            <p className={inter.className}>
              View available time in your calendar for MeTime.
            </p>
          </a>

          <a
            href="/team"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Suggested Activities
            </h2>
            <p className={inter.className}>
              View suggested activites nearby that correlate with your interests. 
            </p>
          </a>

          <a
            href="https://calendar.google.com/calendar/u/0/r"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              My Calendar 
            </h2>
            <p className={inter.className}>
              View your current schedule.&nbsp;
            </p>
          </a>

          <a
            href="/survey"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Add Activities to Calendar 
            </h2>
            <p className={inter.className}>
              Add suggested actitivties to your calendar!&nbsp;
            </p>
          </a>

          <a
            href="/login"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Log Out  
            </h2>
            <p className={inter.className}>
              Log out of your account!
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
